MR_PATTERN = ".*\(.+\) opened merge request.*"
DRAFT_WIP = ".*Draft\:\s*WIP\:.*"
MR_COMMENT = ".*commented on merge request .*"
SPLIT_ID = "[\(\)]"
MENTIONED_IDS = "@([^@\s]+)\s+"
DRAFT_RC = ".*Draft:\s*\d+\s*\d+RC.*"
DRAFT_PBI = ".*Draft\:\s*PBI\:.*"
